import pandas as pd
import pandas_ta as ta

class TechnicalIndicatorEngine:
    """
    Computes technical indicators for financial time series data.
    """
    def __init__(self):
        pass

    def add_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Adds technical indicators to the DataFrame.
        Expects a DataFrame with columns: ['Open', 'High', 'Low', 'Close', 'Volume'].
        """
        # Ensure input is a copy to avoid SettingWithCopy warnings
        df = df.copy()

        # Simple Moving Averages
        df["SMA_10"] = ta.sma(df["Close"], length=10)
        df["SMA_50"] = ta.sma(df["Close"], length=50)

        # Exponential Moving Average
        df["EMA_10"] = ta.ema(df["Close"], length=10)

        # RSI
        df["RSI"] = ta.rsi(df["Close"], length=14)

        # MACD
        macd = ta.macd(df["Close"])
        # pandas_ta returns a DF with MACD, MACD_Signal, MACD_Hist
        df = pd.concat([df, macd], axis=1)

        # Bollinger Bands
        bb = ta.bbands(df["Close"], length=20)
        df = pd.concat([df, bb], axis=1)

        # Stochastic Oscillator
        stoch = ta.stoch(df["High"], df["Low"], df["Close"])
        df = pd.concat([df, stoch], axis=1)
        
        # Fill NaN values generated by lag-based indicators
        df.fillna(0, inplace=True)

        return df
